apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-gke
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-gke
  template:
    metadata:
      labels:
        app: hello-gke
    spec:
      containers:
      - name: hello-gke
        image: gcr.io/geekbang-gke/hello-gke:latest
        ports:
        - containerPort: 5000
